# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Deliverybot Helm Action
      uses: deliverybot/helm@v1.5.0
      with:
        # Helm release name. Will be combined with track if set. (required)
         release: " "
        # Kubernetes namespace name. (required)
         namespace: "test"
        # Helm chart path. If set to "app" this will use the built in helm chart found in this repository. (required)
         chart: " "
        # Helm chart values, expected to be a YAML or JSON string.
         values: " "
        # Task name. If the task is "remove" it will remove the configured helm release.
         dry-run: " "
        # Github repository token. If included and the event is a deployment the deployment_status event will be fired.
         token: " "
        # Additional value files to apply to the helm chart. Expects JSON encoded array or a string.
         value-files: " "
        # Secret variables to include in value file interpolation. Expects JSON encoded map.
         secrets: " "
        # Version of the app, usually commit sha works here.
         version: " "
